version: '3.8'
services:
  iciglobal-be:
    image: ${DOCKER_IMAGE}
    container_name: ${PROJECT_NAME}
    build: .
    working_dir: /iciglobal-be
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/iciglobal-be
    ports:
      - '8085:8000'
    env_file:
      - .env

