# Generated by Django 4.2 on 2025-03-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerperson',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerperson',
            name='second_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
