# Generated by Django 4.2 on 2024-09-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('document_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type_description', models.CharField(max_length=255)),
                ('document_type_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
    ]
