# Generated by Django 4.2 on 2024-10-01 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInCarge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('second_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('second_last_name', models.CharField(max_length=50, null=True)),
                ('document_number', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commom.documenttype')),
            ],
            options={
                'verbose_name': 'Persona Responsable',
                'verbose_name_plural': 'Personas Responsables',
            },
        ),
    ]
