# Generated by Django 4.2 on 2024-10-01 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commom', '0002_personincarge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonInCarge',
            new_name='PersonInCharge',
        ),
    ]
