# Generated by Django 4.2 on 2024-10-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commom', '0003_rename_personincarge_personincharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='document_type_code',
            field=models.CharField(max_length=50),
        ),
    ]
