# Generated by Django 4.2 on 2024-10-01 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commom', '0004_alter_documenttype_document_type_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personincharge',
            name='code',
        ),
    ]
