# Generated by Django 4.2 on 2024-10-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_suppliercompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierperson',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
