# Generated by Django 4.2 on 2024-10-01 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_suppliercompany'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsFromSuppliers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.products')),
                ('supplier_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products_company', to='supplier.suppliercompany')),
                ('supplier_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products_person', to='supplier.supplierperson')),
            ],
            options={
                'verbose_name': 'Product from Supplier',
                'verbose_name_plural': 'Products from Suppliers',
            },
        ),
    ]
