# Generated by Django 4.2 on 2024-10-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsfromsuppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='unique_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
